services:
  db:
    image: mysql:8.4
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - net

networks:
  net:
    driver: bridge